"""updates

Revision ID: 6b7c57bf2ea4
Revises: 
Create Date: 2024-06-09 22:06:52.213638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b7c57bf2ea4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklisted_tokens',
    sa.Column('token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_blacklisted_tokens_token'), 'blacklisted_tokens', ['token'], unique=False)
    op.create_table('corporate_account',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('organization_name', sa.String(), nullable=True),
    sa.Column('organization_description', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('confirm_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corporate_account_email_address'), 'corporate_account', ['email_address'], unique=False)
    op.create_index(op.f('ix_corporate_account_id'), 'corporate_account', ['id'], unique=False)
    op.create_index(op.f('ix_corporate_account_is_active'), 'corporate_account', ['is_active'], unique=False)
    op.create_index(op.f('ix_corporate_account_is_verified'), 'corporate_account', ['is_verified'], unique=False)
    op.create_table('individual_account',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('confirm_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_individual_account_email_address'), 'individual_account', ['email_address'], unique=False)
    op.create_index(op.f('ix_individual_account_id'), 'individual_account', ['id'], unique=False)
    op.create_index(op.f('ix_individual_account_is_active'), 'individual_account', ['is_active'], unique=False)
    op.create_index(op.f('ix_individual_account_is_verified'), 'individual_account', ['is_verified'], unique=False)
    op.create_table('password_reset',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reset_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_in', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_created_at'), 'password_reset', ['created_at'], unique=False)
    op.create_index(op.f('ix_password_reset_expires_in'), 'password_reset', ['expires_in'], unique=False)
    op.create_index(op.f('ix_password_reset_id'), 'password_reset', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_reset_code'), 'password_reset', ['reset_code'], unique=False)
    op.create_table('otp_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('otp_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_in', sa.DateTime(), nullable=True),
    sa.Column('individual_id', sa.UUID(), nullable=True),
    sa.Column('corporate_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['corporate_id'], ['corporate_account.id'], ),
    sa.ForeignKeyConstraint(['individual_id'], ['individual_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_codes_expires_in'), 'otp_codes', ['expires_in'], unique=False)
    op.create_index(op.f('ix_otp_codes_id'), 'otp_codes', ['id'], unique=False)
    op.create_index(op.f('ix_otp_codes_otp_code'), 'otp_codes', ['otp_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_codes_otp_code'), table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_id'), table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_expires_in'), table_name='otp_codes')
    op.drop_table('otp_codes')
    op.drop_index(op.f('ix_password_reset_reset_code'), table_name='password_reset')
    op.drop_index(op.f('ix_password_reset_id'), table_name='password_reset')
    op.drop_index(op.f('ix_password_reset_expires_in'), table_name='password_reset')
    op.drop_index(op.f('ix_password_reset_created_at'), table_name='password_reset')
    op.drop_table('password_reset')
    op.drop_index(op.f('ix_individual_account_is_verified'), table_name='individual_account')
    op.drop_index(op.f('ix_individual_account_is_active'), table_name='individual_account')
    op.drop_index(op.f('ix_individual_account_id'), table_name='individual_account')
    op.drop_index(op.f('ix_individual_account_email_address'), table_name='individual_account')
    op.drop_table('individual_account')
    op.drop_index(op.f('ix_corporate_account_is_verified'), table_name='corporate_account')
    op.drop_index(op.f('ix_corporate_account_is_active'), table_name='corporate_account')
    op.drop_index(op.f('ix_corporate_account_id'), table_name='corporate_account')
    op.drop_index(op.f('ix_corporate_account_email_address'), table_name='corporate_account')
    op.drop_table('corporate_account')
    op.drop_index(op.f('ix_blacklisted_tokens_token'), table_name='blacklisted_tokens')
    op.drop_table('blacklisted_tokens')
    # ### end Alembic commands ###
